export const appCopy = {
  en: {
    "app.error-session_busy": "This Session is open elsewhere. Close it there, then retry.",
    "app.error-session_not_found": "This Session is unavailable. Choose another conversation.",
    "app.error-project_not_found": "The project folder does not exist. Choose another folder.",
    "app.error-invalid_command": "This action could not be processed. Retry.",
    "app.error-not_queued": "This input is no longer queued.",
    "app.error-interaction_stale": "This request is no longer waiting for confirmation.",
    "app.error-internal": "The action could not be completed. Retry.",
    "app.error-disconnected": "Connection lost. Retry.",
    "app.error-superseded": "Another window took over this connection. Retry to continue here.",
    "conversation.action-read": "Read file",
    "conversation.action-edit": "Edited file",
    "conversation.action-delete": "Deleted file",
    "conversation.action-move": "Moved file",
    "conversation.action-search": "Searched",
    "conversation.action-execute": "Ran command",
    "conversation.action-fetch": "Fetched",
    "conversation.action-task": "Started task",
    "conversation.action-other": "Called tool",
    "conversation.permission-allow": "Allow ↵",
    "conversation.permission-session": "Allow for this Session A",
    "conversation.permission-deny": "Deny Esc",
    "conversation.failed": "Failed",
    "conversation.duration": "{{duration}}s",
    "conversation.unavailable": "Output is no longer available",
    "conversation.feed": "Conversation",
    "conversation.group": "Response {{index}}",
    "conversation.jump": "Jump to response {{index}}",
    "conversation.navigation": "Response navigation",
    "conversation.scrollbar": "Conversation scroll position",
    "conversation.running": "Running",
    "conversation.aborted": "Interrupted",
    "conversation.complete": "Completed",
    "conversation.elapsed": "Time spent {{duration}}",
    "conversation.processing": "Processed for {{duration}}",
    "conversation.active-execute": "Running commands",
    "conversation.active-edit": "Editing files",
    "conversation.active-delete": "Deleting files",
    "conversation.active-move": "Moving files",
    "conversation.active-read": "Reading files",
    "conversation.active-search": "Searching files",
    "conversation.active-fetch": "Fetching content",
    "conversation.active-task": "Starting tasks",
    "conversation.active-other": "Calling tools",
    "conversation.analyzing": "Analyzing",
    "conversation.analyzed": "Analysis complete",
    "conversation.activity-execute": "Ran commands",
    "conversation.activity-edit": "Edited files",
    "conversation.activity-read": "Read files",
    "conversation.activity-search": "Searched files",
    "conversation.activity-fetch": "Fetched content",
    "conversation.activity-task": "Started tasks",
    "conversation.activity-other": "Called tools",
    "conversation.activity-separator": ", ",
    "conversation.duration-minutes": "{{minutes}}m {{seconds}}s",
    "conversation.latest": "Jump to latest",
    "conversation.thinking": "Reasoning",
    "conversation.unknown": "Tool outcome is unknown",
    "conversation.continue": "Continue reading at line {{offset}}",
    "conversation.queued": "Queued inputs",
    "conversation.steer": "Send now",
    "conversation.withdraw": "Withdraw",
    "conversation.permission": "Permission required",
    "conversation.decision": "Permission: {{decision}}",
    "conversation.allow": "Allowed",
    "conversation.allow-session": "Allowed for this Session",
    "conversation.deny": "Denied",
    "conversation.summary": "Session summary",
    "conversation.close": "Close summary",
    "conversation.todos": "Tasks",
    "conversation.subagents": "Subagents",
    "conversation.empty": "No tasks or subagents yet",
    "conversation.stale": "This request is no longer pending",

    "app.home": "Home",
    "app.running": "Running",
    "app.waiting": "Waiting for confirmation",
    "app.toggle-sidebar": "Toggle sidebar",
    "app.new-chat": "New chat",
    "app.search": "Search sessions",
    "app.pinned": "Pinned",
    "app.conversations": "Conversations",
    "app.projects": "Projects",
    "app.recent": "Recent",
    "app.workspace": "Workspace",
    "app.welcome": "What would you like to talk about today?",
    "app.project-welcome": "What should we build in {{project}}?",
    "app.add-project": "Add project",
    "app.project-path": "Project folder path",
    "app.add": "Add",
    "app.cancel": "Cancel",
    "app.more": "Session actions",
    "app.summary": "Session summary",
    "app.sidebar-options": "Sidebar options",
    "app.organize": "Organize sidebar",
    "app.expand-all": "Expand all groups",
    "app.collapse-all": "Collapse all groups",
    "app.sort": "Sort sessions",
    "app.updated": "By updated time",
    "app.created": "By created time",
    "app.show": "Show",
    "app.pin": "Pin",
    "app.unpin": "Unpin",
    "app.copy": "Copy",
    "app.copy-id": "Session ID",
    "app.copy-cwd": "Working directory",
    "app.copy-markdown": "Conversation as Markdown",
    "app.open": "Open with",
    "app.finder": "Show in Finder",
    "app.terminal": "Open in Terminal",
    "app.prompt": "Prompt",
    "app.attach": "Attach images",
    "app.remove-image": "Remove {{name}}",
    "app.permission": "Permission mode",
    "app.ask": "Ask",
    "app.ask-description": "Ask before running tools that need permission.",
    "app.auto-review": "Auto review",
    "app.auto-review-description": "Review tool risk automatically; ask when needed.",
    "app.full-access": "Full access",
    "app.full-access-description": "Allow tools without asking for permission.",
    "app.model": "Choose model",
    "app.input": "Input",
    "app.context-window": "Context window",
    "app.thinking": "Reasoning level",
    "app.context": "Context usage",
    "app.system": "System",
    "app.tools": "Tools",
    "app.messages": "Messages",
    "app.opening": "Opening context",
    "app.compactions": "Compaction points",
    "app.no-context": "Context usage will appear after the first reply.",
    "app.disconnected": "Connection lost",
    "app.reconnecting": "Reconnecting…",
    "app.connection-explanation":
      "Runs continue in the sidecar. Messages and pending requests return after reconnecting.",
    "app.retry": "Retry",
    "app.busy": "This Session is open elsewhere. Close it there, then retry.",
    "app.new-in-project": "New chat in {{project}}",
    "app.error": "Action failed: {{message}}",
    "app.no-models": "No authenticated models available",
    "app.images": "Images",
    "app.off": "Off",
    "app.minimal": "Minimal",
    "app.low": "Low",
    "app.medium": "Medium",
    "app.high": "High",
    "app.xhigh": "Extra high",
    "app.max": "Maximum",
  },
  zh: {
    "app.error-session_busy": "这个 Session 正在别处打开，关闭后再试。",
    "app.error-session_not_found": "这个 Session 已不可用，请选择其他会话。",
    "app.error-project_not_found": "项目文件夹不存在，请重新选择。",
    "app.error-invalid_command": "无法处理此操作，请重试。",
    "app.error-not_queued": "此输入已不在队列中。",
    "app.error-interaction_stale": "此请求已不再等待确认。",
    "app.error-internal": "无法完成此操作，请重试。",
    "app.error-disconnected": "连接已断开，请重试。",
    "app.error-superseded": "另一个窗口已接管连接，请重试以在此继续。",
    "conversation.action-read": "读取了文件",
    "conversation.action-edit": "修改了文件",
    "conversation.action-delete": "删除了文件",
    "conversation.action-move": "移动了文件",
    "conversation.action-search": "执行了搜索",
    "conversation.action-execute": "运行了命令",
    "conversation.action-fetch": "获取了内容",
    "conversation.action-task": "启动了任务",
    "conversation.action-other": "调用了工具",
    "conversation.permission-allow": "允许 ↵",
    "conversation.permission-session": "本会话内允许 A",
    "conversation.permission-deny": "拒绝 Esc",
    "conversation.failed": "失败",
    "conversation.duration": "{{duration}}秒",
    "conversation.unavailable": "输出已不可用",
    "conversation.feed": "对话",
    "conversation.group": "回复 {{index}}",
    "conversation.jump": "跳转到回复 {{index}}",
    "conversation.navigation": "回复导航",
    "conversation.scrollbar": "会话滚动位置",
    "conversation.running": "正在执行",
    "conversation.aborted": "已中止",
    "conversation.complete": "已完成",
    "conversation.elapsed": "已用时 {{duration}}",
    "conversation.processing": "已处理 {{duration}}",
    "conversation.active-execute": "正在执行命令",
    "conversation.active-edit": "正在修改文件",
    "conversation.active-delete": "正在删除文件",
    "conversation.active-move": "正在移动文件",
    "conversation.active-read": "正在读取文件",
    "conversation.active-search": "正在搜索文件",
    "conversation.active-fetch": "正在获取内容",
    "conversation.active-task": "正在启动任务",
    "conversation.active-other": "正在调用工具",
    "conversation.analyzing": "分析中",
    "conversation.analyzed": "已完成分析",
    "conversation.activity-execute": "已执行命令",
    "conversation.activity-edit": "已修改文件",
    "conversation.activity-read": "已读取文件",
    "conversation.activity-search": "已搜索文件",
    "conversation.activity-fetch": "已获取内容",
    "conversation.activity-task": "已启动任务",
    "conversation.activity-other": "已调用工具",
    "conversation.activity-separator": "，",
    "conversation.duration-minutes": "{{minutes}}分钟 {{seconds}}秒",
    "conversation.latest": "回到最新回复",
    "conversation.thinking": "推理",
    "conversation.unknown": "工具结果未知",
    "conversation.continue": "从第 {{offset}} 行继续读取",
    "conversation.queued": "排队输入",
    "conversation.steer": "立即发送",
    "conversation.withdraw": "撤回",
    "conversation.permission": "需要权限",
    "conversation.decision": "权限：{{decision}}",
    "conversation.allow": "已允许",
    "conversation.allow-session": "本 Session 内允许",
    "conversation.deny": "已拒绝",
    "conversation.summary": "会话摘要",
    "conversation.close": "关闭摘要",
    "conversation.todos": "任务",
    "conversation.subagents": "子代理",
    "conversation.empty": "暂无任务或子代理",
    "conversation.stale": "此请求已不再等待确认",

    "app.home": "首页",
    "app.running": "正在执行",
    "app.waiting": "等待确认",
    "app.toggle-sidebar": "切换侧栏",
    "app.new-chat": "新聊天",
    "app.search": "搜索会话",
    "app.pinned": "置顶",
    "app.conversations": "对话",
    "app.projects": "项目",
    "app.recent": "最近",
    "app.workspace": "默认工作区",
    "app.welcome": "今天想聊点什么？",
    "app.project-welcome": "你想让我们在 {{project}} 中构建什么？",
    "app.add-project": "添加项目",
    "app.project-path": "项目文件夹路径",
    "app.add": "添加",
    "app.cancel": "取消",
    "app.more": "会话更多",
    "app.summary": "会话摘要",
    "app.sidebar-options": "侧栏选项",
    "app.organize": "整理侧边栏",
    "app.expand-all": "展开全部分组",
    "app.collapse-all": "收起全部分组",
    "app.sort": "会话排序方式",
    "app.updated": "按更新时间",
    "app.created": "按创建时间",
    "app.show": "显示",
    "app.pin": "置顶",
    "app.unpin": "取消置顶",
    "app.copy": "复制",
    "app.copy-id": "Session ID",
    "app.copy-cwd": "工作目录",
    "app.copy-markdown": "Markdown 形式的对话",
    "app.open": "打开方式",
    "app.finder": "在 Finder 中显示",
    "app.terminal": "在终端中打开",
    "app.prompt": "输入消息",
    "app.attach": "添加图片",
    "app.remove-image": "移除 {{name}}",
    "app.permission": "权限模式",
    "app.ask": "询问",
    "app.ask-description": "执行需要权限的工具前询问。",
    "app.auto-review": "自动审查",
    "app.auto-review-description": "自动审查工具风险，必要时询问。",
    "app.full-access": "完全访问",
    "app.full-access-description": "无需询问即可允许工具执行。",
    "app.model": "选择模型",
    "app.input": "输入类型",
    "app.context-window": "上下文窗口",
    "app.thinking": "推理档次",
    "app.context": "上下文用量",
    "app.system": "系统",
    "app.tools": "工具",
    "app.messages": "消息",
    "app.opening": "开场上下文",
    "app.compactions": "压缩点",
    "app.no-context": "首次回复后显示上下文用量。",
    "app.disconnected": "连接已断开",
    "app.reconnecting": "正在重新连接…",
    "app.connection-explanation": "Run 仍在 sidecar 中继续，重连后会补齐消息和待确认项。",
    "app.retry": "重试",
    "app.busy": "这个 Session 正在别处打开，关闭后再试。",
    "app.new-in-project": "在 {{project}} 中新建会话",
    "app.error": "操作失败：{{message}}",
    "app.no-models": "没有已认证的模型",
    "app.images": "图片",
    "app.off": "关闭",
    "app.minimal": "最少",
    "app.low": "低",
    "app.medium": "中",
    "app.high": "高",
    "app.xhigh": "超高",
    "app.max": "最高",
  },
} as const;
