export const appCopy = {
  en: {
    "app.home": "Home",
    "app.running": "Running",
    "app.waiting": "Waiting for confirmation",
    "app.toggle-sidebar": "Toggle sidebar",
    "app.new-chat": "New chat",
    "app.search": "Search sessions",
    "app.pinned": "Pinned",
    "app.conversations": "Conversations",
    "app.projects": "Projects",
    "app.recent": "Recent",
    "app.workspace": "Workspace",
    "app.welcome": "What would you like to talk about today?",
    "app.project-welcome": "What should we build in {{project}}?",
    "app.add-project": "Add project",
    "app.project-path": "Project folder path",
    "app.add": "Add",
    "app.cancel": "Cancel",
    "app.more": "Session actions",
    "app.summary": "Session summary",
    "app.sidebar-options": "Sidebar options",
    "app.organize": "Organize sidebar",
    "app.expand-all": "Expand all groups",
    "app.collapse-all": "Collapse all groups",
    "app.sort": "Sort sessions",
    "app.updated": "By updated time",
    "app.created": "By created time",
    "app.show": "Show",
    "app.pin": "Pin",
    "app.unpin": "Unpin",
    "app.copy": "Copy",
    "app.copy-id": "Session ID",
    "app.copy-cwd": "Working directory",
    "app.copy-markdown": "Conversation as Markdown",
    "app.open": "Open with",
    "app.finder": "Show in Finder",
    "app.terminal": "Open in Terminal",
    "app.prompt": "Prompt",
    "app.attach": "Attach images",
    "app.remove-image": "Remove {{name}}",
    "app.permission": "Permission mode",
    "app.ask": "Ask",
    "app.ask-description": "Ask before running tools that need permission.",
    "app.auto-review": "Auto review",
    "app.auto-review-description": "Review tool risk automatically; ask when needed.",
    "app.full-access": "Full access",
    "app.full-access-description": "Allow tools without asking for permission.",
    "app.model": "Choose model",
    "app.input": "Input",
    "app.context-window": "Context window",
    "app.thinking": "Reasoning level",
    "app.context": "Context usage",
    "app.system": "System",
    "app.tools": "Tools",
    "app.messages": "Messages",
    "app.opening": "Opening context",
    "app.compactions": "Compaction points",
    "app.no-context": "Context usage will appear after the first reply.",
    "app.disconnected": "Connection lost",
    "app.reconnecting": "Reconnecting…",
    "app.connection-explanation":
      "Runs continue in the sidecar. Messages and pending requests return after reconnecting.",
    "app.retry": "Retry",
    "app.busy": "This Session is open elsewhere. Close it there, then retry.",
    "app.new-in-project": "New chat in {{project}}",
    "app.error": "Action failed: {{message}}",
    "app.no-models": "No authenticated models available",
    "app.images": "Images",
    "app.off": "Off",
    "app.minimal": "Minimal",
    "app.low": "Low",
    "app.medium": "Medium",
    "app.high": "High",
    "app.xhigh": "Extra high",
    "app.max": "Maximum",
  },
  zh: {
    "app.home": "首页",
    "app.running": "正在执行",
    "app.waiting": "等待确认",
    "app.toggle-sidebar": "切换侧栏",
    "app.new-chat": "新聊天",
    "app.search": "搜索会话",
    "app.pinned": "置顶",
    "app.conversations": "对话",
    "app.projects": "项目",
    "app.recent": "最近",
    "app.workspace": "默认工作区",
    "app.welcome": "今天想聊点什么？",
    "app.project-welcome": "你想让我们在 {{project}} 中构建什么？",
    "app.add-project": "添加项目",
    "app.project-path": "项目文件夹路径",
    "app.add": "添加",
    "app.cancel": "取消",
    "app.more": "会话更多",
    "app.summary": "会话摘要",
    "app.sidebar-options": "侧栏选项",
    "app.organize": "整理侧边栏",
    "app.expand-all": "展开全部分组",
    "app.collapse-all": "收起全部分组",
    "app.sort": "会话排序方式",
    "app.updated": "按更新时间",
    "app.created": "按创建时间",
    "app.show": "显示",
    "app.pin": "置顶",
    "app.unpin": "取消置顶",
    "app.copy": "复制",
    "app.copy-id": "Session ID",
    "app.copy-cwd": "工作目录",
    "app.copy-markdown": "Markdown 形式的对话",
    "app.open": "打开方式",
    "app.finder": "在 Finder 中显示",
    "app.terminal": "在终端中打开",
    "app.prompt": "输入消息",
    "app.attach": "添加图片",
    "app.remove-image": "移除 {{name}}",
    "app.permission": "权限模式",
    "app.ask": "询问",
    "app.ask-description": "执行需要权限的工具前询问。",
    "app.auto-review": "自动审查",
    "app.auto-review-description": "自动审查工具风险，必要时询问。",
    "app.full-access": "完全访问",
    "app.full-access-description": "无需询问即可允许工具执行。",
    "app.model": "选择模型",
    "app.input": "输入类型",
    "app.context-window": "上下文窗口",
    "app.thinking": "推理档次",
    "app.context": "上下文用量",
    "app.system": "系统",
    "app.tools": "工具",
    "app.messages": "消息",
    "app.opening": "开场上下文",
    "app.compactions": "压缩点",
    "app.no-context": "首次回复后显示上下文用量。",
    "app.disconnected": "连接已断开",
    "app.reconnecting": "正在重新连接…",
    "app.connection-explanation": "Run 仍在 sidecar 中继续，重连后会补齐消息和待确认项。",
    "app.retry": "重试",
    "app.busy": "这个 Session 正在别处打开，关闭后再试。",
    "app.new-in-project": "在 {{project}} 中新建会话",
    "app.error": "操作失败：{{message}}",
    "app.no-models": "没有已认证的模型",
    "app.images": "图片",
    "app.off": "关闭",
    "app.minimal": "最少",
    "app.low": "低",
    "app.medium": "中",
    "app.high": "高",
    "app.xhigh": "超高",
    "app.max": "最高",
  },
} as const;
