export const componentCopy = {
  zh: {
    "component.close": "关闭",
    "component.close-modal": "关闭对话框",
    "component.dismiss-modal": "关闭对话框",
    "component.select": "选择",
    "component.type-a-command-or-search": "输入命令或搜索…",
    "component.results": "结果",
    "component.close-command-palette": "关闭命令面板",
    "component.command-palette": "命令面板",
    "component.commands": "命令",
    "component.no-results-found": "未找到结果。",
    "component.message": "消息",
    "component.conversation": "对话",
    "component.message-navigation": "消息导航",
    "component.section-navigation": "章节导航",
    "component.submitting": "正在提交",
    "component.approved": "已批准",
    "component.rejected": "已拒绝",
    "component.changes-requested": "已请求修改",
    "component.response-submitted": "已提交回复",
    "component.input-required": "需要输入",
    "component.approval-required": "需要批准",
    "component.approve": "批准",
    "component.submit-response": "提交回复",
    "component.dismiss": "关闭",
    "component.previous-question": "上一题",
    "component.next-question": "下一题",
    "component.add-another-response": "添加其他回复…",
    "component.responding": "正在回复",
    "component.writing": "正在写入",
    "component.ready": "就绪",
    "component.copied": "已复制",
    "component.copy-code": "复制代码",
    "component.running": "正在运行",
    "component.completed": "已完成",
    "component.failed": "失败",
    "component.cancelled": "已取消",
    "component.copy-result": "复制结果",
    "component.run-again": "重新运行",
    "component.applying-changes": "正在应用更改",
    "component.changes-applied": "更改已应用",
    "component.file-changes": "文件更改",
    "component.copy-diff": "复制差异",
    "component.ask-the-agent-to-do-something": "让代理执行任务…",
    "component.prompt": "输入",
    "component.add-to-prompt": "添加到输入",
    "component.choose-model": "选择模型",
    "component.stop-generating": "停止生成",
    "component.send-prompt": "发送输入",
    "component.helpful": "有帮助",
    "component.not-helpful": "没有帮助",
    "component.copy-response": "复制回复",
    "component.retry-response": "重试回复",
    "component.sources": "来源",
    "component.source": "来源",
    "component.searched-the-web": "已搜索网络",
    "component.searching-the-web": "正在搜索网络…",
    "component.running-tools": "正在运行工具…",
    "component.working-through-the-run": "正在执行…",
    "component.working-through-it": "正在处理…",
    "component.thinking": "正在思考",
    "component.reading-the-context": "正在阅读上下文",
    "component.connecting-the-details": "正在整理细节",
    "component.forming-a-response": "正在构思回复",
    "component.reasoning": "推理",
    "component.churning": "正在处理",
    "component.in-progress": "进行中",
    "component.pending": "待处理",
    "component.agent-task-list": "代理任务列表",
    "component.to-dos": "待办事项",
    "component.show-more": "展开",
    "component.show-less": "收起",
    "component.approving": "正在批准",
    "component.denied": "已拒绝",
    "component.allow-this-tool-to-run": "允许此工具运行？",
    "component.loading": "正在加载",
    "component.view-details": "查看详情",
    "component.allow-once": "允许一次",
    "component.always-allow": "本会话内允许",
    "component.deny": "拒绝",
    "component.request-changes": "请求修改",
    "component.reject": "拒绝",
    "component.custom-response": "自定义回复",
    "component.select-all-that-apply": "选择所有适用项",
    "component.no-tasks-yet": "暂无任务。",
    "component.thought-for": "思考耗时",
    "component.select-an-option": "选择一项",
    "component.search": "搜索…",
    "component.navigate": "导航",
    "component.open": "打开",
    "component.close-drawer": "关闭抽屉",
    "component.context-menu": "上下文菜单",
    "component.done": "完成",
    "component.try-again": "重试",
    "component.popover-effects": "浮层视觉效果",
    "component.no-tasks": "暂无任务",
    "component.question-count": "问题 {{current}} / {{total}}",
    "component.task-count": "已完成 {{done}} / {{total}} 项任务",
    "component.more-count": "另有 {{count}} 项",
    "component.tool-count": "已运行 {{count}} 个工具",
    "component.trace-count": "{{tools}} 次工具调用，{{messages}} 条消息",
    "component.step-count": "已完成 {{count}} 个步骤",
    "component.gallery": "组件验收",
    "component.light": "浅色",
    "component.dark": "深色",
    "component.menu": "菜单",
    "component.open-project": "打开项目",
    "component.context": "上下文",
    "component.context-detail": "系统、工具和消息共用上下文窗口。",
    "component.review-command": "执行前请检查命令。",
    "component.command": "命令",
    "component.theme": "主题",
    "component.keyboard": "键盘",
    "component.message-navigation-item": "跳转到 {{sender}} 消息 {{current}} / {{total}}",
    "component.assistant": "助手",
    "component.user": "用户",
  },
  en: {
    "component.close": "Close",
    "component.close-modal": "Close modal",
    "component.dismiss-modal": "Dismiss modal",
    "component.select": "Select",
    "component.type-a-command-or-search": "Type a command or search…",
    "component.results": "Results",
    "component.close-command-palette": "Close command palette",
    "component.command-palette": "Command palette",
    "component.commands": "Commands",
    "component.no-results-found": "No results found.",
    "component.message": "Message",
    "component.conversation": "Conversation",
    "component.message-navigation": "Message navigation",
    "component.section-navigation": "Section navigation",
    "component.submitting": "Submitting",
    "component.approved": "Approved",
    "component.rejected": "Rejected",
    "component.changes-requested": "Changes requested",
    "component.response-submitted": "Response submitted",
    "component.input-required": "Input required",
    "component.approval-required": "Approval required",
    "component.approve": "Approve",
    "component.submit-response": "Submit response",
    "component.dismiss": "Dismiss",
    "component.previous-question": "Previous question",
    "component.next-question": "Next question",
    "component.add-another-response": "Add another response…",
    "component.responding": "Responding",
    "component.writing": "Writing",
    "component.ready": "Ready",
    "component.copied": "Copied",
    "component.copy-code": "Copy code",
    "component.running": "Running",
    "component.completed": "Completed",
    "component.failed": "Failed",
    "component.cancelled": "Cancelled",
    "component.copy-result": "Copy result",
    "component.run-again": "Run again",
    "component.applying-changes": "Applying changes",
    "component.changes-applied": "Changes applied",
    "component.file-changes": "File changes",
    "component.copy-diff": "Copy diff",
    "component.ask-the-agent-to-do-something": "Ask the agent to do something…",
    "component.prompt": "Prompt",
    "component.add-to-prompt": "Add to prompt",
    "component.choose-model": "Choose model",
    "component.stop-generating": "Stop generating",
    "component.send-prompt": "Send prompt",
    "component.helpful": "Helpful",
    "component.not-helpful": "Not helpful",
    "component.copy-response": "Copy response",
    "component.retry-response": "Retry response",
    "component.sources": "sources",
    "component.source": "source",
    "component.searched-the-web": "Searched the web",
    "component.searching-the-web": "Searching the web…",
    "component.running-tools": "Running tools…",
    "component.working-through-the-run": "Working through the run…",
    "component.working-through-it": "Working through it…",
    "component.thinking": "Thinking",
    "component.reading-the-context": "Reading the context",
    "component.connecting-the-details": "Connecting the details",
    "component.forming-a-response": "Forming a response",
    "component.reasoning": "Reasoning",
    "component.churning": "Churning",
    "component.in-progress": "In progress",
    "component.pending": "Pending",
    "component.agent-task-list": "Agent task list",
    "component.to-dos": "To-dos",
    "component.show-more": "Show more",
    "component.show-less": "Show less",
    "component.approving": "Approving",
    "component.denied": "Denied",
    "component.allow-this-tool-to-run": "Allow this tool to run?",
    "component.loading": "Loading",
    "component.view-details": "View details",
    "component.allow-once": "Allow once",
    "component.always-allow": "Always allow",
    "component.deny": "Deny",
    "component.request-changes": "Request changes",
    "component.reject": "Reject",
    "component.custom-response": "Custom response",
    "component.select-all-that-apply": "Select all that apply",
    "component.no-tasks-yet": "No tasks yet.",
    "component.thought-for": "Thought for",
    "component.select-an-option": "Select an option",
    "component.search": "Search…",
    "component.navigate": "Navigate",
    "component.open": "Open",
    "component.close-drawer": "Close drawer",
    "component.context-menu": "Context menu",
    "component.done": "Done",
    "component.try-again": "Try again",
    "component.popover-effects": "Popover visual effects",
    "component.no-tasks": "No tasks yet",
    "component.question-count": "Question {{current}} of {{total}}",
    "component.task-count": "{{done}} of {{total}} tasks completed",
    "component.more-count": "+{{count}} more",
    "component.tool-count": "Ran {{count}} tools",
    "component.trace-count": "{{tools}} tool calls, {{messages}} messages",
    "component.step-count": "Completed {{count}} steps",
    "component.gallery": "Component gallery",
    "component.light": "Light",
    "component.dark": "Dark",
    "component.menu": "Menu",
    "component.open-project": "Open project",
    "component.context": "Context",
    "component.context-detail": "System, tools and messages share the context window.",
    "component.review-command": "Review the command before execution.",
    "component.command": "Command",
    "component.theme": "Theme",
    "component.keyboard": "Keyboard",
    "component.message-navigation-item": "Go to {{sender}} message {{current}} of {{total}}",
    "component.assistant": "assistant",
    "component.user": "user",
  },
} as const;
