"""Generate terminal avatars and previews from the authoritative palette grid."""

from pathlib import Path
import html
import json
import re
import struct
import zlib

ROOT = Path(__file__).parent
DATA = json.loads((ROOT / "frames.json").read_text())
WIDTH, HEIGHT = DATA["width"], DATA["height"]
PALETTE = DATA["palette"]


def rgb(color):
    return tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))


def ansi(grid):
    result = []
    for y in range(0, HEIGHT, 2):
        out, previous = "", None
        for x in range(WIDTH):
            up, lo = grid[y][x], grid[y + 1][x]
            if up == lo == ".":
                style, char = "\x1b[0m", " "
            else:
                upper = up if up != "." else lo
                style = "\x1b[38;2;" + ";".join(map(str, rgb(PALETTE[upper]))) + "m"
                style += ("\x1b[48;2;" + ";".join(map(str, rgb(PALETTE[lo]))) + "m"
                          if up != "." and lo != "." else "\x1b[49m")
                char = "▄" if up == "." else "▀"
            if style != previous:
                out += style
                previous = style
            out += char
        result.append(out + "\x1b[0m")
    return "\n".join(result) + "\n"


def ansi_html(text):
    """Preview the actual ANSI glyphs and SGR colors, not a replacement image."""
    foreground, background, output = "inherit", "transparent", []
    for piece in re.split(r"(\x1b\[[0-9;]*m)", text):
        if piece.startswith("\x1b["):
            values = [int(n) for n in piece[2:-1].split(";")]
            if values == [0]:
                foreground, background = "inherit", "transparent"
            elif values == [49]:
                background = "transparent"
            elif values[:2] == [38, 2]:
                foreground = "rgb(" + ",".join(map(str, values[2:])) + ")"
            elif values[:2] == [48, 2]:
                background = "rgb(" + ",".join(map(str, values[2:])) + ")"
        else:
            for char in piece:
                if char == "\n":
                    output.append("\n")
                    continue
                up = foreground if char == "▀" else background
                lo = foreground if char == "▄" else background
                output.append(f'<span class="cell" style="--up:{up};--lo:{lo}">{html.escape(char)}</span>')
    return "".join(output)


def png(grid):
    # Lossless enlarged pixel proof generated from the same palette grid.
    scale = 16
    width, height = WIDTH * scale, HEIGHT * scale
    rows = bytearray()
    for y in range(height):
        rows.append(0)
        for x in range(width):
            symbol = grid[y // scale][x // scale]
            rows.extend(rgb(PALETTE.get(symbol, "#101318")))
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(rows)) + chunk(b"IEND", b""))


frames = {frame["name"]: frame["rows"] for frame in DATA["frames"]}
for name, grid in frames.items():
    assert len(grid) == HEIGHT and all(len(row) == WIDTH for row in grid)
    assert set("".join(grid)) <= set(PALETTE) | {"."}
    (ROOT / f"{name}.ansi").write_text(ansi(grid))
(ROOT / "standard.png").write_bytes(png(frames["standard"]))
source = "// Generated by brand/render.py from brand/frames.json.\n"
source += f"export const AVATAR_WIDTH = {WIDTH};\nexport const AVATAR_HEIGHT = {HEIGHT // 2};\n\n"
source += "export const AVATAR_PALETTE: Readonly<Record<string, `#${string}` | undefined>> = " + json.dumps(PALETTE, indent=2) + ";\n\n"
source += "export const AVATAR_FRAMES = " + json.dumps(frames, indent=2) + ";\n\n"
source += "export type AvatarPose = keyof typeof AVATAR_FRAMES;\n"
(ROOT.parent / "packages/coding-agent/src/tui/components/logo/avatar-frames.ts").write_text(source)
cards = "".join(f'<article><pre>{ansi_html(ansi(grid))}</pre><p>{html.escape(name)}</p></article>' for name, grid in frames.items())
page = '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rukie · 角色头像</title>
<style>body{margin:32px;background:#101318;color:#eee;font-family:system-ui}h1{color:#E85693;font-weight:500}main{display:flex;gap:32px;flex-wrap:wrap}pre{font-family:monospace;font-size:16px;line-height:1.2;white-space:pre;margin:0}.cell{display:inline-block;width:1ch;height:1.2em;vertical-align:top;color:transparent;background:linear-gradient(to bottom,var(--up) 0 50%,var(--lo) 50% 100%)}p{color:#aaa}</style>
<h1>Rukie · 高清角色头像</h1><img src="rukie-avatar.png" alt="Rukie 高清透明头像" width="280" height="280" style="object-fit:contain"><p>Kitty 终端优先显示完整 PNG；下方为字符回退。</p><p>40 × 28 像素 → 40 列 × 14 行 ANSI；#E85693 主题色。预览解释实际半块字符与 SGR 颜色。</p><main>__CARDS__</main></html>'''
(ROOT / "preview.html").write_text(page.replace("__CARDS__", cards))
print("Generated avatar TypeScript, ANSI poses, PNG proof and HTML preview from frames.json.")
