// Rukie night-spirit v2: original pixel art. Editable design assets live in brand.
export const SPIRIT_WIDTH = 40;
export const SPIRIT_HEIGHT = 14;

export const SPIRIT_PALETTE: Readonly<Record<string, `#${string}` | undefined>> = {
  D: "#3B506F",
  B: "#ADC8EE",
  L: "#EDF5FF",
  S: "#789BCE",
  T: "#5D7DAC",
  E: "#202E46",
  W: "#FFFFFF",
  C: "#CCB2CC",
  P: "#527AAF",
  Z: "#202C3E",
};

export const SPIRIT_FRAMES = {
  standard: [
    "........................................",
    "....................D...................",
    "...................DLDD.................",
    ".............DDDDDDLLLLDDD..............",
    "...........DDLLLLLLLLLLLLLDDD...........",
    "..........DLLLLLLLLLLLLLLLLLLD..........",
    ".........DLLLLLLLLLLLLLLLLLLLSD.........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    ".......DBLLLLEEEBBBBBBBEEEBBBSSSD.......",
    ".......DBLLLEWWEEBBBBBEWWEEBBSSSD.......",
    ".....DDBBBBBELEEEBBBBBELEEEBBSSSD.......",
    "....DBBBBBBBEEEEEBBBBBEEEEEBBSSSD.......",
    "...DBBBBBBBBBEEEBBBBBBBEEEBBBSSSSDD.....",
    "...DBBBBBBCCCBBBBBBBBBBBBBBCCCSSSSSD....",
    "....DBBBBBBBBBBBPBBBBBBBBBBBBSSSSSSSD...",
    ".....DDBBBBBBBBBBPBBBBBBBBBBBSSSSSSSD...",
    ".......DBBBBBBBBBBPBBBBBBSSSSSSSSSDD....",
    ".......DBBBBBBBBBPBBBBBBBSSSSSSSSD......",
    ".......DBBBBBBBBPBBBBPPPPSSSSSSSD.......",
    "........DSSSSSSDDSSSSSSSDDTTTTTD........",
    "........DSSSSSD..DSSSSSD..DTTTTD........",
    ".........DSSSD....DSSSD....DTTD.........",
    "..........DDD......DDD......DD..........",
    "........................................",
    "........................................",
    ".............ZZZZZZZZZZZZZZZ............",
    "................ZZZZZZZZZ...............",
  ],
  blink: [
    "........................................",
    "....................D...................",
    "...................DLDD.................",
    ".............DDDDDDLLLLDDD..............",
    "...........DDLLLLLLLLLLLLLDDD...........",
    "..........DLLLLLLLLLLLLLLLLLLD..........",
    ".........DLLLLLLLLLLLLLLLLLLLSD.........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    ".......DBLLLBBBBBBBBBBBBBBBBBSSSD.......",
    ".......DBLLLBBBBBBBBBBBBBBBBBSSSD.......",
    ".....DDBBBBBEBBBEBBBBBEBBBEBBSSSD.......",
    "....DBBBBBBBBEEEBBBBBBBEEEBBBSSSD.......",
    "...DBBBBBBBBBBBBBBBBBBBBBBBBBSSSSDD.....",
    "...DBBBBBBCCCBBBBBBBBBBBBBBCCCSSSSSD....",
    "....DBBBBBBBBBBBPBBBBBBBBBBBBSSSSSSSD...",
    ".....DDBBBBBBBBBBPBBBBBBBBBBBSSSSSSSD...",
    ".......DBBBBBBBBBBPBBBBBBSSSSSSSSSDD....",
    ".......DBBBBBBBBBPBBBBBBBSSSSSSSSD......",
    ".......DBBBBBBBBPBBBBPPPPSSSSSSSD.......",
    "........DSSSSSSDDSSSSSSSDDTTTTTD........",
    "........DSSSSSD..DSSSSSD..DTTTTD........",
    ".........DSSSD....DSSSD....DTTD.........",
    "..........DDD......DDD......DD..........",
    "........................................",
    "........................................",
    ".............ZZZZZZZZZZZZZZZ............",
    "................ZZZZZZZZZ...............",
  ],
  float: [
    "....................D...................",
    "...................DLDD.................",
    ".............DDDDDDLLLLDDD..............",
    "...........DDLLLLLLLLLLLLLDDD...........",
    "..........DLLLLLLLLLLLLLLLLLLD..........",
    ".........DLLLLLLLLLLLLLLLLLLLSD.........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    "........DLLLLBBBBBBBBBBBBBBBBSSD........",
    ".......DBLLLLEEEBBBBBBBEEEBBBSSSD.......",
    ".......DBLLLEWWEEBBBBBEWWEEBBSSSD.......",
    ".....DDBBBBBELEEEBBBBBELEEEBBSSSD.......",
    "....DBBBBBBBEEEEEBBBBBEEEEEBBSSSD.......",
    "...DBBBBBBBBBEEEBBBBBBBEEEBBBSSSSDD.....",
    "...DBBBBBBCCCBBBBBBBBBBBBBBCCCSSSSSD....",
    "....DBBBBBBBBBBBPBBBBBBBBBBBBSSSSSSSD...",
    ".....DDBBBBBBBBBBPBBBBBBBBBBBSSSSSSSD...",
    ".......DBBBBBBBBBBPBBBBBBSSSSSSSSSDD....",
    ".......DBBBBBBBBBPBBBBBBBSSSSSSSSD......",
    ".......DBBBBBBBBPBBBBPPPPSSSSSSSD.......",
    "........DSSSSSSDDSSSSSSSDDTTTTTD........",
    "........DSSSSSD..DSSSSSD..DTTTTD........",
    ".........DSSSD....DSSSD....DTTD.........",
    "..........DDD......DDD......DD..........",
    "........................................",
    "........................................",
    "........................................",
    "........................................",
    "................ZZZZZZZZZ...............",
  ],
};

export type SpiritPose = keyof typeof SPIRIT_FRAMES;
