export {
  Box,
  Image,
  type ImageProps,
  Text,
  TextInput,
  createTextInputHistory,
  type BoxProps,
  type TextProps,
  type TextInputProps,
  Static,
  ScrollBox,
  type ScrollBoxProps,
  Spinner,
  type SpinnerProps,
  type StaticProps,
} from "./components";
export type { ScrollHandle, ScrollSnapshot, ScrollAnchor } from "./scroll";
export { render, type RenderOptions } from "./renderer";
export {
  useInput,
  useTerminalSize,
  useTerminalFocus,
  useTerminalGraphics,
  ClockProvider,
  useAnimationFrame,
} from "./hooks";
export type { InputEvent, Key } from "./input";
export {
  dark,
  light,
  type Theme,
  ThemeProvider,
  useTheme,
  figures,
  toolKindColor,
  Tooltip,
  TooltipProvider,
  useDismissTooltip,
  SyntaxHighlightedText,
  highlightSyntax,
  type SyntaxRun,
  rgb,
  hex,
  interpolateColor,
  type Rgb,
  sweep,
  StatusIcon,
  type StatusIconProps,
  Divider,
  type DividerProps,
  ListItem,
  type ListItemProps,
  HintLine,
  type HintLineProps,
  ThemedText,
  ThemedBox,
  ThemedTextInput,
  type ThemeColor,
  type ThemedTextProps,
  type ThemedBoxProps,
  type ThemedTextInputProps,
} from "./design-system";

export type { TerminalGraphics } from "./terminal";
